Group membership implementation
googleinterns/step250-2020 pull request #20
Opened 2020-09-07 15:37 UTC by TsarN

2020-09-08 16:45 UTC, PrabSG commented on coffee-chats/src/main/webapp/src/components/GroupMemberListItem.tsx
> +            </ListItemSecondaryAction> : null}
Rather than using ternary operator { cond ? tsx element : null }, you can just use {cond && tsx element}, which is a bit cleaner.

2020-09-08 17:10 UTC, PrabSG requested changes

2020-09-08 17:10 UTC, PrabSG commented on coffee-chats/src/test/java/com/google/step/coffee/PermissionCheckerTest.java
> +  private boolean doGroupTest(Status prev, Status cur) {
Change method name to something more descriptive, it is not particularly clear. Perhaps `changeGroupStatusSelf`?

2020-09-08 17:10 UTC, PrabSG commented on coffee-chats/src/test/java/com/google/step/coffee/PermissionCheckerTest.java
> +  private boolean doGroupTestOther(Status my, Status prev, Status cur) {
Change to `changeGroupStatusOther`?

2020-09-08 17:10 UTC, PrabSG commented on coffee-chats/src/test/java/com/google/step/coffee/servlets/GroupListServletTest.java
> +    membershipEntity.setProperty("status", GroupMembership.Status.ADMINISTRATOR.toString());
Shouldn't `"test_user"` have status `Status.OWNER`?

2020-09-10 12:18 UTC, PrabSG approved these changes

2020-09-11 09:38 UTC, DarthGandalf approved these changes

2020-09-11 09:40 UTC, merged