Group search & tags
googleinterns/step250-2020 pull request #23
Opened 2020-09-10 14:38 UTC by TsarN

2020-09-11 15:56 UTC, PrabSG requested changes

2020-09-11 15:56 UTC, PrabSG commented on coffee-chats/src/main/webapp/src/components/TagsInput.tsx
> +            return (
nit: Arrow functions with no body only a return statement can be converted to:
`func = (params) => (
    <tsx />
)`
So no need for the return, acting almost like a map function

2020-09-14 12:10 UTC, PrabSG approved these changes

2020-09-14 13:30 UTC, med0b1011 approved these changes

2020-09-14 13:31 UTC, merged